<?php
/**
 * @version 8.0
 */
/**
 * MOD:- ADVANCED CUSTOM FIELDS
 *
 * SAMPLE VIEW PARTIAL
 */

/* @var \Cube\Form\Element $element */
$label = $element->getLabel();
$description = $element->getDescription();
$subtitle = $element->getSubtitle();

if (!$element->isHidden()) { ?>
    <?php if (!empty($subtitle)) { ?>
        <h5 class="subtitle">
            <?php echo $subtitle; ?>
        </h5>
    <?php } ?>

    <div class="float-left w-50 form-element-50">
        <div class="form-group row">
<!--            <label for="" class="col-lg-6 col-form-label">-->
<!--                --><?php //if (!empty($label)) { ?>
<!--                    --><?php //echo $label; ?>
<!--                --><?php //} ?>
<!--            </label>-->
            <div class="col col-form-input">
                <?php echo $element->render(); ?>
                <?php if (!empty($description)) { ?>
                    <small class="form-text text-muted">
                        <?php echo $description; ?>
                    </small>
                <?php } ?>
            </div>
        </div>
    </div>
<?php } ?>